language: ruby
rvm:
  - 2.3
  - 2.4
gemfile:
  - gemfiles/rails50.gemfile
  - gemfiles/rails51.gemfile
before_install:
  - gem install bundler -v 1.15.3
before_script:
  - cd spec/dummy
  - bundle exec rake db:migrate RAILS_ENV=test
  - cd ../..
script: bundle exec rspec
