default: &default
  adapter: mysql2
  pool: 10
  timeout: 5000
  charset: utf8mb4
  collation: utf8mb4_bin
  encoding: utf8mb4

development:
  <<: *default
  database: activerecord_nested_scope_development

test:
  <<: *default
  database: activerecord_nested_scope_test
  host: 127.0.0.1
  username: root

production:
  <<: *default
  database: activerecord_nested_scope_production
